version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: php -S 0.0.0.0:8001 -t public
    ports:
      - 8001:8001
  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: php bin/phpunit